require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

# 👇 Enable dynamic frameworks
use_frameworks! :linkage => :dynamic

target 'caterstation' do
  config = use_native_modules!

   pod 'Firebase', :modular_headers => true
   pod 'FirebaseCoreInternal', :modular_headers => true
   pod 'FirebaseCore', :modular_headers => true
   pod 'FirebaseMessaging', :modular_headers => true




  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false
  )

  # 👇 Add modular headers only for this pod
  #pod 'react-native-video', :path => '../node_modules/react-native-video', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
